---
kind: pipeline
type: docker
name: docker-jamserver amd64

platform:
  os: linux
  arch: amd64

environment:
  DOCKER_BUILDKIT: 1

steps:
  - name: Fetch submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive
  - name: Build cbix/jamulus
    image: plugins/docker
    depends_on:
      - Fetch submodules
    settings:
      repo: cbix/jamulus
      tags: latest-amd64
      dockerfile: jamulus/Dockerfile
      username: cbix
      password:
        from_secret: docker-pass
    when:
      event:
        - push
  - name: Build cbix/jamulus on PR
    image: plugins/docker
    depends_on:
      - Fetch submodules
    settings:
      repo: cbix/jamulus
      tags: latest-amd64
      dockerfile: jamulus/Dockerfile
      dry_run: true
    when:
      event:
        - pull_request
  - name: Build cbix/ninjam
    image: plugins/docker
    settings:
      repo: cbix/ninjam
      tags: latest-amd64
      dockerfile: ninjam/Dockerfile
      username: cbix
      password:
        from_secret: docker-pass
    when:
      event:
        - push
  - name: Build cbix/ninjam on PR
    image: plugins/docker
    settings:
      repo: cbix/ninjam
      tags: latest-amd64
      dockerfile: ninjam/Dockerfile
      dry_run: true
    when:
      event:
        - pull_request

trigger:
  event:
    - push
    - pull_request
    - cron
  branch:
    - master
  cron:
    - ""
    - docker

---
kind: pipeline
type: docker
name: docker-jamserver arm64

platform:
  os: linux
  arch: arm64

environment:
  DOCKER_BUILDKIT: 1

steps:
  - name: Fetch submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive
  - name: Build cbix/jamulus
    image: plugins/docker
    depends_on:
      - Fetch submodules
    settings:
      repo: cbix/jamulus
      tags: latest-arm64
      dockerfile: jamulus/Dockerfile
      username: cbix
      password:
        from_secret: docker-pass
    when:
      event:
        - push
  - name: Build cbix/jamulus on PR
    image: plugins/docker
    depends_on:
      - Fetch submodules
    settings:
      repo: cbix/jamulus
      tags: latest-arm64
      dockerfile: jamulus/Dockerfile
      dry_run: true
    when:
      event:
        - pull_request
  - name: Build cbix/ninjam
    image: plugins/docker
    depends_on:
      - Fetch submodules
    settings:
      repo: cbix/ninjam
      tags: latest-arm64
      dockerfile: ninjam/Dockerfile
      username: cbix
      password:
        from_secret: docker-pass
    when:
      event:
        - push
  - name: Build cbix/ninjam on PR
    image: plugins/docker
    depends_on:
      - Fetch submodules
    settings:
      repo: cbix/ninjam
      tags: latest-arm64
      dockerfile: ninjam/Dockerfile
      dry_run: true
    when:
      event:
        - pull_request

trigger:
  event:
    - push
    - pull_request
    - cron
  branch:
    - master
  cron:
    - ""
    - docker

---
kind: pipeline
type: docker
name: docker-jamserver manifest

clone:
  disable: true

depends_on:
  - docker-jamserver amd64
  - docker-jamserver arm64

steps:
  - name: cbix/jamulus manifest
    image: plugins/manifest
    settings:
      target: cbix/jamulus:latest
      template: cbix/jamulus:latest-ARCH
      platforms:
        - linux/amd64
        - linux/arm64
      ignore_missing: true
      username: cbix
      password:
        from_secret: docker-pass
  - name: cbix/ninjam manifest
    image: plugins/manifest
    settings:
      target: cbix/ninjam:latest
      template: cbix/ninjam:latest-ARCH
      platforms:
        - linux/amd64
        - linux/arm64
      ignore_missing: true
      username: cbix
      password:
        from_secret: docker-pass

trigger:
  event:
    - push
    - cron
  branch:
    - master
  cron:
    - ""
    - docker
