---
kind: pipeline
type: docker
name: docker-jamserver amd64

platform:
  os: linux
  arch: amd64

environment:
  DOCKER_BUILDKIT: 1
  MAKEFLAGS: "-j4"

volumes:
  - name: repo
    temp: {}

steps:
  - name: Fetch submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive
  - name: Build ninjam apk
    image: alpinelinux/build-base
    volumes:
      - name: repo
        path: /repo
    environment:
      REPODEST: /repo
    user: root
    commands:
      - abuild-keygen -nai
      #- cp -r apkbuilds/packages/ninjam-server ~/; cd ~/ninjam-server
      - (cd apkbuilds/packages/ninjam-server; abuild -Fr)
      - find /repo/
  - name: debug
    image: alpine
    volumes:
      - name: repo
        path: /drone/src/repo
    commands:
      - ls -la
  - name: Build cbix/ninjam
    image: plugins/docker
    volumes:
      - name: repo
        path: /drone/src/repo
    settings:
      repo: cbix/ninjam
      tags: latest
      dockerfile: ninjam/Dockerfile
      daemon_off: true
      username: cbix
      password:
        from_secret: docker-pass

trigger:
  event:
    - push
    - pull_request
    - cron
  branch:
    - master
  cron:
    - ""
    - docker
