---
kind: pipeline
type: docker
name: docker-jamserver amd64

platform:
  os: linux
  arch: amd64

environment:
  DOCKER_BUILDKIT: 1
  MAKEFLAGS: "-j4"

steps:
  - name: Fetch submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive
  - name: Build jamulus apk
    image: alpinelinux/build-base
    depends_on:
      - Fetch submodules
    user: root
    commands:
      - abuild-keygen -nai
      - cd apkbuilds/packages/jamulus
      - abuild -FrP $${DRONE_WORKSPACE}/repo
  - name: Build cbix/jamulus
    image: plugins/docker
    depends_on:
      - Build jamulus apk
    settings:
      repo: cbix/jamulus
      tags: latest
      dockerfile: jamulus/Dockerfile
      username: cbix
      password:
        from_secret: docker-pass
  - name: Build ninjam apk
    image: alpinelinux/build-base
    depends_on:
      - Fetch submodules
    user: root
    commands:
      - abuild-keygen -nai
      - cd apkbuilds/packages/ninjam-server
      - abuild -FrP $${DRONE_WORKSPACE}/repo
  - name: Build cbix/ninjam
    image: plugins/docker
    depends_on:
      - Build ninjam apk
    settings:
      repo: cbix/ninjam
      tags: latest
      dockerfile: ninjam/Dockerfile
      username: cbix
      password:
        from_secret: docker-pass

trigger:
  event:
    - push
    - pull_request
    - cron
  branch:
    - master
  cron:
    - ""
    - docker
